In [24]:

######## snakemake preamble start (automatically inserted, do not edit) ########
import sys; sys.path.extend(['/home/lmf/anaconda3/envs/Mosaic_workflow/lib/python3.9/site-packages', '/home/lmf/.cache/snakemake/snakemake/source-cache/runtime-cache/tmpa2lkxs7i/file/home/lmf/apps/MOSAIC/mosaic/rules/../notebooks', '/home/lmf/apps/MOSAIC/mosaic/rules/../notebooks']); import pickle; snakemake = pickle.loads(b'\x80\x04\x95D\x17\x00\x00\x00\x00\x00\x00\x8c\x10snakemake.script\x94\x8c\tSnakemake\x94\x93\x94)\x81\x94}\x94(\x8c\x05input\x94\x8c\x0csnakemake.io\x94\x8c\nInputFiles\x94\x93\x94)\x81\x94(\x8c]/home/lmf/PhylloVir/VIRAL_WORLD/VIRAL_FRACTION/05_vOTUs/checkV_merged_quality_summary.tot.txt\x94\x8c}/home/lmf/PhylloVir/VIRAL_WORLD/VIRAL_FRACTION/05_vOTUs/combined_positive_viral_contigs_derreplicated_rep_seq.tot_95-85.clstr\x94\x8cu/home/lmf/PhylloVir/VIRAL_WORLD/VIRAL_FRACTION/05_vOTUs/combined_positive_viral_contigs.tot_derreplicated_cluster.tsv\x94e}\x94(\x8c\x06_names\x94}\x94(\x8c\x0emerged_summary\x94K\x00N\x86\x94\x8c\x0ccluster_file\x94K\x01N\x86\x94\x8c\x16derreplicated_clusters\x94K\x02N\x86\x94u\x8c\x12_allowed_overrides\x94]\x94(\x8c\x05index\x94\x8c\x04sort\x94eh\x18\x8c\tfunctools\x94\x8c\x07partial\x94\x93\x94h\x06\x8c\x19Namedlist._used_attribute\x94\x93\x94\x85\x94R\x94(h\x1e)}\x94\x8c\x05_name\x94h\x18sNt\x94bh\x19h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x19sNt\x94bh\x10h\nh\x12h\x0bh\x14h\x0cub\x8c\x06output\x94h\x06\x8c\x0bOutputFiles\x94\x93\x94)\x81\x94(\x8cX/home/lmf/PhylloVir/VIRAL_WORLD/VIRAL_FRACTION/05_vOTUs/vOTU_clustering_rep_list.tot.csv\x94\x8cl/home/lmf/PhylloVir/VIRAL_WORLD/VIRAL_FRACTION/05_vOTUs/vOTU_clustering_rep_list_checkv_per_category.tot.csv\x94\x8cW/home/lmf/PhylloVir/VIRAL_WORLD/VIRAL_FRACTION/05_vOTUs/new_references_clusters.tot.csv\x94e}\x94(h\x0e}\x94(\x8c\x0frepresentatives\x94K\x00N\x86\x94\x8c\x11checkv_categories\x94K\x01N\x86\x94\x8c\x0cnew_clusters\x94K\x02N\x86\x94uh\x16]\x94(h\x18h\x19eh\x18h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x18sNt\x94bh\x19h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x19sNt\x94bh1h,h3h-h5h.ub\x8c\x06params\x94h\x06\x8c\x06Params\x94\x93\x94)\x81\x94(]\x94(\x8c\x04vBRB\x94\x8c\x06vBRB_T\x94\x8c\x04vF1A\x94\x8c\x06vF1A_T\x94\x8c\x04vF1B\x94\x8c\x06vF1B_T\x94\x8c\x04vF1C\x94\x8c\x06vF1C_T\x94\x8c\x05vF1aB\x94\x8c\x07vF1aB_T\x94\x8c\x04vF23\x94\x8c\x04vF2A\x94\x8c\x06vF2A_T\x94\x8c\x04vF2B\x94\x8c\x06vF2B_T\x94\x8c\x04vF2C\x94\x8c\x06vF2C_T\x94\x8c\x05vF2aA\x94\x8c\x07vF2aA_T\x94\x8c\x04vF3A\x94\x8c\x06vF3A_T\x94\x8c\x04vF3B\x94\x8c\x06vF3B_T\x94\x8c\x04vF3C\x94\x8c\x06vF3C_T\x94\x8c\x03vFL\x94\x8c\x07vFL_amp\x94\x8c\x03vN1\x94\x8c\x05vN1_T\x94\x8c\x03vN2\x94\x8c\x05vN2_T\x94\x8c\x03vN3\x94\x8c\x05vN3_T\x94\x8c\x03vNW\x94\x8c\x05vNW_T\x94\x8c\x04vNWd\x94\x8c\x06vNWd_T\x94\x8c\x04vO1A\x94\x8c\x06vO1A_T\x94\x8c\x04vO1B\x94\x8c\x06vO1B_T\x94\x8c\x04vO1C\x94\x8c\x06vO1C_T\x94\x8c\x05vO1aB\x94\x8c\x07vO1aB_T\x94\x8c\x04vO2A\x94\x8c\x06vO2A_T\x94\x8c\x04vO2B\x94\x8c\x06vO2B_T\x94\x8c\x04vO2C\x94\x8c\x06vO2C_T\x94\x8c\x05vO2aA\x94\x8c\x07vO2aA_T\x94\x8c\x04vO3A\x94\x8c\x06vO3A_T\x94\x8c\x04vO3B\x94\x8c\x06vO3B_T\x94\x8c\x04vO3C\x94\x8c\x06vO3C_T\x94\x8c\x03vOL\x94\x8c\x07vOL_amp\x94\x8c\x04vS1B\x94\x8c\x06vS1B_T\x94\x8c\x04vS1C\x94\x8c\x06vS1C_T\x94\x8c\x04vS2B\x94\x8c\x06vS2B_T\x94\x8c\x04vS2C\x94\x8c\x06vS2C_T\x94\x8c\x04vS3B\x94\x8c\x06vS3B_T\x94\x8c\x04vS3C\x94\x8c\x06vS3C_T\x94\x8c\x03vSE\x94\x8c\x05vSE_T\x94\x8c\x04vSEd\x94\x8c\x06vSEd_T\x94\x8c\x03vSW\x94\x8c\x05vSW_T\x94\x8c\x04vSWd\x94\x8c\x06vSWd_T\x94\x8c\x04vWRB\x94\x8c\x06vWRB_T\x94\x8c\x03vZ1\x94\x8c\x05vZ1_T\x94\x8c\x03vZ2\x94\x8c\x05vZ2_T\x94\x8c\x03vZ3\x94\x8c\x05vZ3_T\x94e\x8c9/home/lmf/PhylloVir/VIRAL_WORLD/VIRAL_FRACTION/03_CONTIGS\x94\x8c:/home/lmf/PhylloVir/VIRAL_WORLD/VIRAL_FRACTION/04_VIRAL_ID\x94\x88\x89e}\x94(h\x0e}\x94(\x8c\x07samples\x94K\x00N\x86\x94\x8c\ncontig_dir\x94K\x01N\x86\x94\x8c\tviral_dir\x94K\x02N\x86\x94\x8c\x0bsubassembly\x94K\x03N\x86\x94\x8c\x0ecross_assembly\x94K\x04N\x86\x94uh\x16]\x94(h\x18h\x19eh\x18h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x18sNt\x94bh\x19h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x19sNt\x94bh\xa2hDh\xa4h\x9eh\xa6h\x9fh\xa8\x88h\xaa\x89ub\x8c\twildcards\x94h\x06\x8c\tWildcards\x94\x93\x94)\x81\x94\x8c\x03tot\x94a}\x94(h\x0e}\x94\x8c\x08sampling\x94K\x00N\x86\x94sh\x16]\x94(h\x18h\x19eh\x18h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x18sNt\x94bh\x19h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x19sNt\x94b\x8c\x08sampling\x94h\xb9ub\x8c\x07threads\x94K\x01\x8c\tresources\x94h\x06\x8c\tResources\x94\x93\x94)\x81\x94(K\x01K\x01\x8c\x04/tmp\x94e}\x94(h\x0e}\x94(\x8c\x06_cores\x94K\x00N\x86\x94\x8c\x06_nodes\x94K\x01N\x86\x94\x8c\x06tmpdir\x94K\x02N\x86\x94uh\x16]\x94(h\x18h\x19eh\x18h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x18sNt\x94bh\x19h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x19sNt\x94bh\xd0K\x01h\xd2K\x01h\xd4h\xcdub\x8c\x03log\x94h\x06\x8c\x03Log\x94\x93\x94)\x81\x94\x8cY/home/lmf/PhylloVir/VIRAL_WORLD/VIRAL_FRACTION/NOTEBOOKS/05_vOTU_representative.tot.ipynb\x94a}\x94(h\x0e}\x94\x8c\x08notebook\x94K\x00N\x86\x94sh\x16]\x94(h\x18h\x19eh\x18h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x18sNt\x94bh\x19h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x19sNt\x94bh\xe6h\xe3ub\x8c\x06config\x94}\x94(\x8c\tinput_dir\x94\x8c:/home/lmf/PhylloVir/VIRAL_WORLD/VIRAL_FRACTION/00_RAW_DATA\x94\x8c\tkraken_db\x94\x8c\x1b/home/lmf/db/KRAKEN/kraken/\x94\x8c\rkrakenUniq_db\x94\x8c\x1e/home/lmf/db/KRAKEN/KrakenUniq\x94\x8c\necc_memory\x94M\x80>\x8c\x0bsubassembly\x94\x88\x8c\x1cadditional_reference_contigs\x94\x8cE/home/lmf/PhylloVir/VIRAL_WORLD/VIRAL_FRACTION/reference_phages.fasta\x94\x8c\x0eassembly_stats\x94\x88\x8c\x0bsubsampling\x94\x88\x8c\x0fmin_votu_length\x94M\x10\'\x8c\x0crun_vcontact\x94\x88\x8c\x11microbial_spacers\x94\x8cd/home/lmf/PhylloVir/VIRAL_WORLD/BACTERIAL_FRACTION/07_ANNOTATION/minced_predicted_spacers_spacers.fa\x94\x8c\x0bresults_dir\x94\x8c\x00\x94\x8c\nmetagenome\x94\x88\x8c\tmicrobial\x94\x89\x8c\x10operating_system\x94\x8c\x05linux\x94\x8c\x0bforward_tag\x94\x8c\x02R1\x94\x8c\x0breverse_tag\x94\x8c\x02R2\x94\x8c\x0cnanopore_tag\x94\x8c\x08nanopore\x94\x8c\x0fnanopore_pooled\x94\x89\x8c\x14nanopore_pooled_name\x94\x8c\x03raw\x94\x8c\x0elong_assembler\x94\x8c\x04canu\x94\x8c\x0bgenome_size\x94\x8c\x0320m\x94\x8c\x13trimmomatic_leading\x94\x8c\x0220\x94\x8c\x14trimmomatic_trailing\x94\x8c\x0220\x94\x8c\x17trimmomatic_window_size\x94\x8c\x014\x94\x8c\x1atrimmomatic_window_quality\x94\x8c\x0220\x94\x8c\x12trimmomatic_minlen\x94\x8c\x0250\x94\x8c\x10nanopore_quality\x94\x8c\x0210\x94\x8c\x0fnanopore_minlen\x94M\xe8\x03\x8c\x0fnanopore_maxlen\x94J\x80\x96\x98\x00\x8c\tVirSorter\x94\x89\x8c\x0ecross_assembly\x94\x89\x8c\x16representative_contigs\x94j\x04\x01\x00\x00\x8c\x08sra_list\x94j\x04\x01\x00\x00\x8c\x07p_ident\x94\x8c\x0295\x94\x8c\x0bkmer_window\x94\x8c\x0525000\x94\x8c\x08min_norm\x94\x8c\x010\x94\x8c\x08max_norm\x94\x8c\x03100\x94\x8c\rmax_subsample\x94\x8c\x0850000000\x94\x8c\x07min_len\x94\x8c\x041000\x94\x8c\x07min_cov\x94\x8c\x012\x94\x8c\x11contaminants_list\x94j\x04\x01\x00\x00\x8c\radapters_file\x94\x8c\x0badapters.fa\x94\x8c\x11ambiguous_mapping\x94\x8c\x03all\x94\x8c\x0ebasecalled_dir\x94\x8c\x10data/basecalled/\x94\x8c\x0bimgvr_blast\x94\x89\x8c\x13reference_databases\x94\x8c\x1eIMGVR GenBankViral RefSeqViral\x94\x8c\x08IMGVR_db\x94\x8c!/home/lmf/db/IMG_VR_2022-12-19_7/\x94\x8c\x0eRefSeqViral_db\x94\x8c6/home/lmf/db/RefSeqViral/RefSeq_viral_2022_03_10.fasta\x94\x8c\x16RefSeqViral_protein_db\x94\x8c>/home/lmf/db/RefSeqViral/ORFs/RefSeq_viral_2022_03_10_ORFs.faa\x94\x8c\x0fGenBankViral_db\x94\x8c7/home/lmf/db/GenBankViral/GenBankViral_2022_03_10.fasta\x94\x8c\x17GenBankViral_protein_db\x94\x8c?/home/lmf/db/GenBankViral/ORFs/GenBankViral_2022_03_10_ORFs.faa\x94\x8c\x08blast_db\x94\x8c\x1fdb/ncbi/NCBI_viral_proteins.faa\x94\x8c\x0cvirSorter_db\x94\x8c\x1bdb/VirSorter/virsorter-data\x94\x8c\x0ckraken_db_nt\x94\x8c\x17/home/lmf/db/KRAKEN/nt/\x94\x8c\x0fkraken_db_human\x94\x8c\x13db/kraken2_human_db\x94\x8c\x0ckraken_tools\x94\x8c\x11tools/KrakenTools\x94\x8c\x0bbracken_dir\x94\x8c\rtools/Bracken\x94\x8c\nweesam_dir\x94\x8c\x0ctools/weeSAM\x94\x8c\tcheckv_db\x94\x8c\x11db/checkv-db-v1.5\x94\x8c\tcheckm_db\x94\x8c\x0cdb/checkm-db\x94\x8c\x08iphop_db\x94\x8c\x0bdb/iphop_db\x94\x8c\rtaxmyphage_db\x94\x8c\x10db/taxmyphage_db\x94\x8c\x0csourmash_sig\x94\x8c7/home/lmf/db/SOURMASH/matrix_09_42_sourmash_k31.sig.zip\x94\x8c\x10sourmash_rocksdb\x94\x8c;/home/lmf/db/SOURMASH/matrix_09_42_sourmash_k31.sig.rocksdb\x94\x8c\x0csourmash_tax\x94\x8c9/home/lmf/db/SOURMASH/taxonomy/taxonomy_matrix_strain.csv\x94\x8c\x08canu_dir\x94\x8c\x1etools/canu-2.0/Linux-amd64/bin\x94\x8c\x12PhaGCN_newICTV_dir\x94\x8c\x14tools/PhaGCN_newICTV\x94\x8c\tquast_dir\x94\x8c\x11tools/quast-5.0.2\x94\x8c\rvirSorter_dir\x94\x8c\x0ftools/VirSorter\x94\x8c\x07WTP_dir\x94\x8c\ttools/WTP\x94\x8c\rvirFinder_dir\x94\x8c\x0ftools/VirFinder\x94\x8c\x0eclusterONE_dir\x94\x8c\x10tools/clusterONE\x94\x8c\x0cvcontact_dir\x94\x8c\x0ftools/vcontact2\x94\x8c\x08run_DRAM\x94\x89\x8c\x1areference_genomes_vcontact\x94\x8c\x04None\x94\x8c\rtaxonomy_file\x94\x8c1db/vcontact2/formatting_taxonomy_affiliations.csv\x94\x8c\ngenomad_db\x94\x8c\rdb/genomad_db\x94\x8c\x07DRAM_db\x94\x8c\ndb/DRAM_db\x94\x8c\tgtdbtk_db\x94\x8c\ndb/GTDB-Tk\x94\x8c\nmmseqs_dir\x94\x8c\rtools/MMseqs2\x94\x8c\x08viga_dir\x94\x8c\ntools/viga\x94\x8c\tpiler_dir\x94\x8c\x11tools/pilercr1.06\x94\x8c\x07trf_dir\x94\x8c\ttools/TRF\x94\x8c\x0bvibrant_dir\x94\x8c\rtools/VIBRANT\x94\x8c\x0eviridic_folder\x94\x8c\x17tools/viridic_v1.0_r3.6\x94\x8c\x0fsra_toolkit_dir\x94\x8c tools/sratoolkit.2.10.0-ubuntu64\x94\x8c\x07ALE_dir\x94\x8c\ttools/ALE\x94\x8c\x08wish_dir\x94\x8c\ntools/WIsH\x94\x8c\nminced_dir\x94\x8c\x0ctools/minced\x94\x8c\x07dion_db\x94\x8c\x0cdb/dionSetDB\x94u\x8c\x04rule\x94\x8c\x1aselect_vOTU_representative\x94\x8c\x0fbench_iteration\x94N\x8c\tscriptdir\x94\x8c//home/lmf/apps/MOSAIC/mosaic/rules/../notebooks\x94ub.'); from snakemake.logging import logger; logger.printshellcmds = True; import os; os.chdir(r'/home/lmf/apps/MOSAIC/mosaic');
######## snakemake preamble end #########

In [25]:
import pandas as pd

In [26]:
input_merged_summary=snakemake.input.merged_summary
input_cluster_file=snakemake.input.cluster_file
input_derreplicated_clusters=snakemake.input.derreplicated_clusters
output_representatives=snakemake.output.representatives
output_checkv_categories=snakemake.output.checkv_categories
output_new_clusters=snakemake.output.new_clusters

In [27]:
# Read and preprocess the clustered_df DataFrame
clustered_df = pd.read_csv(input_cluster_file, sep="\t", names=["rep", "mem"])
clustered_df["mem"] = clustered_df["mem"].str.split(",")
clustered_df = clustered_df.explode('mem').reset_index(drop=True)

# Read and preprocess the checkv_df_vOTUs DataFrame
checkv_df_vOTUs = pd.read_csv(input_merged_summary, sep="\t",
                            names= ["contig_id_vOTU", "contig_length_vOTU", "provirus_vOTU", "proviral_length_vOTU",
                           "gene_count_vOTU", "viral_genes_vOTU", "host_genes_vOTU", "checkv_quality_vOTU",
                           "miuvig_quality_vOTU", "completeness_vOTU", "completeness_method_vOTU",
                           "contamination_vOTU", "kmer_freq_vOTU", "warnings_vOTU"])
checkv_df_vOTUs = checkv_df_vOTUs[["contig_id_vOTU", "contig_length_vOTU", "checkv_quality_vOTU",
                                   "completeness_vOTU", "provirus_vOTU", "warnings_vOTU"]]
checkv_df_vOTUs["contig_length_vOTU"] = checkv_df_vOTUs["contig_length_vOTU"].astype(float)
checkv_df_vOTUs["completeness_vOTU"] = checkv_df_vOTUs["completeness_vOTU"].astype(float)
checkv_df_vOTUs=checkv_df_vOTUs.groupby("contig_id_vOTU").first().reset_index()

# Create copies of the checkv_df_vOTUs DataFrame
checkv_df_rep = checkv_df_vOTUs.copy()
checkv_df_rep.columns = ["contig_id_rep", "contig_length_rep", "checkv_quality_rep", "completeness_rep",
                         "provirus_rep", "warnings_rep"]

# Merge DataFrames and drop unnecessary columns
merged_df = clustered_df.merge(checkv_df_rep, left_on="rep", right_on="contig_id_rep", how="left") \
                        .merge(checkv_df_vOTUs, left_on="mem", right_on="contig_id_vOTU", how="left")
merged_df = merged_df.drop(['contig_id_vOTU', 'contig_id_rep'], axis=1)
merged_df[['completeness_vOTU', 'contig_length_vOTU', 'completeness_rep']] = merged_df[
    ['completeness_vOTU', 'contig_length_vOTU', 'completeness_rep']].fillna(0)
merged_df["completeness_vOTU"] = merged_df["completeness_vOTU"].astype(float)
merged_df["contig_length_vOTU"] = merged_df["contig_length_vOTU"].astype(float)

# Choose the contig with the highest completeness and the lowest contig length
merged_df_best = merged_df[merged_df.groupby(['rep'], sort=False)['completeness_vOTU'].transform(max) == merged_df['completeness_vOTU']]
merged_df_best = merged_df_best[merged_df_best.groupby(['rep'], sort=False)['contig_length_vOTU'].transform(min) == merged_df_best['contig_length_vOTU']]
merged_df_best = merged_df_best.groupby(['rep']).first().reset_index()

# Select final singletons and grouped contigs based on checkv quality
final_singletons = merged_df_best[merged_df_best["rep"] == merged_df_best["mem"]]["rep"].tolist()

merged_df_diff = merged_df_best[merged_df_best["rep"] != merged_df_best["mem"]]
merged_df_diff = merged_df_diff.replace({'Complete': 4, 'High-quality': 3, 'Medium-quality': 2,'Low-quality': 1, 'Not-determined': 1})

# Choose representatives based on checkv quality comparison
merged_df_greatherthan = merged_df_diff[merged_df_diff["checkv_quality_rep"] > merged_df_diff["checkv_quality_vOTU"]]
gr1 = merged_df_greatherthan["rep"].tolist()

merged_df_smallerthan = merged_df_diff[merged_df_diff["checkv_quality_rep"] < merged_df_diff["checkv_quality_vOTU"]]
gr2 = merged_df_smallerthan["mem"].tolist()

merged_df_equal1 = merged_df_diff[(merged_df_diff["checkv_quality_rep"] == merged_df_diff["checkv_quality_vOTU"]) & 
                                       (merged_df_diff["warnings_rep"]!="contig >1.5x longer than expected genome length")]

gr3 = merged_df_equal1["rep"].tolist()

merged_df_equal2 = merged_df_diff[(merged_df_diff["checkv_quality_rep"] == merged_df_diff["checkv_quality_vOTU"]) & 
                                       (merged_df_diff["warnings_rep"]=="contig >1.5x longer than expected genome length")]
gr4 = merged_df_equal2[merged_df_equal2["warnings_vOTU"]=="contig >1.5x longer than expected genome length"]["rep"].tolist()

gr5 = merged_df_equal2[merged_df_equal2["warnings_vOTU"]!="contig >1.5x longer than expected genome length"]["mem"].tolist()

# merged_df_greatherthan.sort_values(by="contig_length_vOTU")[-30:]
representatives = final_singletons + gr1 + gr2 + gr3 +  gr4 + gr5
final_df_rep = checkv_df_vOTUs[checkv_df_vOTUs['contig_id_vOTU'].isin(representatives)]

# Sort the final_df_rep DataFrame by contig_length_vOTU column
final_df_rep.sort_values(by="contig_length_vOTU")

/tmp/ipykernel_817481/1508260202.py:33: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  merged_df_best = merged_df[merged_df.groupby(['rep'], sort=False)['completeness_vOTU'].transform(max) == merged_df['completeness_vOTU']]
/tmp/ipykernel_817481/1508260202.py:34: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  merged_df_best = merged_df_best[merged_df_best.groupby(['rep'], sort=False)['contig_length_vOTU'].transform(min) == merged_df_best['contig_length_vOTU']]

,contig_id_vOTU,contig_length_vOTU,checkv_quality_vOTU,completeness_vOTU,provirus_vOTU,warnings_vOTU
1414102,vO2aA_NODE_29156_length_1000_cov_3.568254,1000.0,Low-quality,1.77,No,None
1414105,vO2aA_NODE_29172_length_1000_cov_2.227513,1000.0,Not-determined,NaN,No,no viral genes detected
1414095,vO2aA_NODE_29140_length_1000_cov_4.875132,1000.0,Low-quality,0.82,No,None
1414098,vO2aA_NODE_29146_length_1000_cov_4.171429,1000.0,Not-determined,NaN,No,no viral genes detected
1414099,vO2aA_NODE_29148_length_1000_cov_4.016931,1000.0,Not-determined,NaN,No,no viral genes detected
...,...,...,...,...,...,...
1753672,vOL_amp_NODE_1_length_304831_cov_44.623320,304831.0,Complete,100.00,No,None
609460,vFL_40_NODE_1_length_322093_cov_128.112235,322093.0,Complete,100.00,No,contig >1.5x longer than expected genome length
426004,vF2C_60_NODE_1_length_338063_cov_23.006112,338063.0,Complete,100.00,No,None
1723073,vOL_NODE_1_length_354460_cov_25.463219,354460.0,High-quality,98.28,No,None
185854,vF1A_50_NODE_1_length_354857_cov_43.570902,354857.0,Complete,100.00,No,None

In [28]:
final_df_rep.groupby("checkv_quality_vOTU").size().to_csv(output_checkv_categories, index=True, header=False)
final_df_rep.groupby("checkv_quality_vOTU").size().to_frame()

                          0
checkv_quality_vOTU
Complete                432
High-quality            939
Low-quality          115172
Medium-quality         1765
Not-determined        69614

In [29]:
derreplicated_df=pd.read_csv(input_derreplicated_clusters, sep="\t", names=["rep_d", "mem_d"])
derreplicated_df=derreplicated_df.merge(clustered_df, left_on="rep_d", right_on="mem")
derreplicated_df=derreplicated_df[["rep", "mem_d"]]
# Make a copy of the original DataFrame `derreplicated_df` to avoid modifying it directly
derreplicated_df_fixed = derreplicated_df.copy()

# Create a set of unique values from the "rep" column in `derreplicated_df` for quick lookup
rep_set = set(derreplicated_df["rep"])

# # Loop over each new reference (in `contig_id_vOTU` column) from `final_df_rep`
for new_reference in final_df_rep["contig_id_vOTU"]:
    
    # Check if the new reference is not already in the existing set of "rep" values
    if new_reference not in rep_set:
        
        # Find the old reference in `derreplicated_df` where `mem` column matches the `new_reference`
        # Get the corresponding value from the "rep" column
        old_reference = derreplicated_df.loc[derreplicated_df["mem_d"] == new_reference, "rep"].iloc[0]
        
        # Update `derreplicated_df_fixed` so that all occurrences of `old_reference` in "rep" are replaced by `new_reference`
        derreplicated_df_fixed.loc[derreplicated_df_fixed["rep"] == old_reference, "rep"] = new_reference

In [30]:
for rep, group in derreplicated_df_fixed.groupby("rep"):
    # Check if `rep` does not start with "P_" or "E_"
    if not rep.startswith("P_") and not rep.startswith("E_") and not rep.startswith("APSE_"):
        
        # Check if any value in the "mem_d" column starts with "P_" or "E_"
        if group["mem_d"].str.startswith("P_").any() or group["mem_d"].str.startswith("E_").any() or group["mem_d"].str.startswith("APSE_").any():
            
            # Print the matching `rep` value
            print(f"Match found for rep: {rep}")
            
            # Find values in "mem_d" that start with "P_" or "E_"
            matching_mem_d = group["mem_d"][group["mem_d"].str.startswith("P_") | group["mem_d"].str.startswith("E_") | group["mem_d"].str.startswith("APSE_")]
            
            # Collect `mem_d` and `contig_length_rep` pairs for sorting
            mem_d_lengths = []
            
            # Loop over each matching mem_d value to get the corresponding contig length from checkv_df_rep
            for mem_d in matching_mem_d:
                # Find the contig length for each matching `mem_d` in `checkv_df_rep`
                contig_length = checkv_df_rep.loc[checkv_df_rep["contig_id_rep"] == mem_d, "contig_length_rep"]
                if not contig_length.empty:
                    mem_d_lengths.append((mem_d, contig_length.iloc[0]))

            # Sort the list by `contig_length_rep` (second item in tuple)
            mem_d_lengths.sort(key=lambda x: x[1])

            # Print sorted `mem_d` values with their contig lengths
            print("Matching mem_d values sorted by contig length:")
            for mem_d, length in mem_d_lengths:
                print(f"{mem_d}: {length}")
                
            # Set new_reference as the longest (last in sorted list)
            new_reference = mem_d_lengths[-1][0]  # Get only the `mem_d` part
            print("new_reference:", new_reference)
            
            # Replace the "rep" column values where "rep" == rep with new_reference
            derreplicated_df_fixed.loc[derreplicated_df_fixed["rep"] == rep, "rep"] = new_reference

derreplicated_df_fixed.to_csv(output_new_clusters, sep="\t", index=False)

Match found for rep: vF3B_NODE_24_length_40004_cov_49.953766
Matching mem_d values sorted by contig length:
E_aphidicola_B03_5_pp3_cluster_6: 40755.0
E_aphidicola_B09_9_pp3_cluster_6: 40757.0
E_aphidicola_W03_4_pp3_cluster_6: 40757.0
E_aphidicola_B03_3_pp3_cluster_6: 40758.0
E_aphidicola_B09_1_pp3_cluster_6: 40758.0
E_aphidicola_B03_2_pp3_cluster_6: 40759.0
E_aphidicola_W03_10_pp3_cluster_6: 40759.0
E_aphidicola_W03_5_pp3_cluster_6: 40759.0
E_aphidicola_Z9_1_pp3_cluster_15: 41268.0
E_aphidicola_Z9_3_pp3_cluster_15: 41269.0
new_reference: E_aphidicola_Z9_3_pp3_cluster_15
Match found for rep: vN2_T_70_NODE_2_length_36083_cov_80.951649
Matching mem_d values sorted by contig length:
APSE_wheat_IDAHO: 40108.0
APSE_wheat: 41352.0
new_reference: APSE_wheat
Match found for rep: vO1C_60_NODE_39_length_91650_cov_42.601747_provirus_1_69952
Matching mem_d values sorted by contig length:
P_trivialis_B08_3_pp2_cluster_28: 33988.0
new_reference: P_trivialis_B08_3_pp2_cluster_28
Match found for rep: vO2B_40_NODE_73_length_40791_cov_107.257880
Matching mem_d values sorted by contig length:
E_aphidicola_W03_5_pp2_cluster_1: 40476.0
E_aphidicola_B03_5_pp2_cluster_1: 40528.0
E_aphidicola_B03_2_pp2_cluster_1: 40531.0
E_aphidicola_B03_3_pp2_cluster_1: 40532.0
E_aphidicola_W03_4_pp2_cluster_1: 40532.0
E_aphidicola_W11_1_pp2_cluster_1: 40533.0
E_aphidicola_B01_2_pp1_cluster_1: 40533.0
E_aphidicola_W03_10_pp2_cluster_1: 40533.0
E_aphidicola_B01_10_pp1_cluster_1: 40535.0
new_reference: E_aphidicola_B01_10_pp1_cluster_1
Match found for rep: vO2C_20_NODE_149_length_43230_cov_31.333781_provirus_3928_37044
Matching mem_d values sorted by contig length:
E_aphidicola_Z9_3_pp4_cluster_16: 31999.0
new_reference: E_aphidicola_Z9_3_pp4_cluster_16
Match found for rep: vS1B_60_NODE_186_length_32123_cov_72.213234
Matching mem_d values sorted by contig length:
E_aphidicola_B06_1_pp1_cluster_9: 16022.0
E_aphidicola_B06_6_pp1_cluster_9: 16023.0
E_aphidicola_W06_2_pp1_cluster_9: 16024.0
E_aphidicola_B06_2_pp1_cluster_9: 16024.0
E_aphidicola_W06_8_pp1_cluster_9: 16026.0
new_reference: E_aphidicola_W06_8_pp1_cluster_9
Match found for rep: vS2B_70_NODE_207_length_31500_cov_14.121355
Matching mem_d values sorted by contig length:
E_aphidicola_N2_6_pp2_cluster_14: 31399.0
E_aphidicola_N2_1_pp2_cluster_14: 31400.0
E_aphidicola_N2_3_pp2_cluster_14: 31405.0
new_reference: E_aphidicola_N2_3_pp2_cluster_14

In [35]:
# Save representative contig IDs to a CSV file
derreplicated_df_fixed.groupby("rep").first().reset_index()[["rep"]].to_csv(output_representatives, index=False, header=False)

In [36]:
derreplicated_df_fixed.groupby("rep").first()

                                                                                    mem_d
rep
APSE_wheat                                    vF2A_90_NODE_403_length_9299_cov_351.645392
E_aphidicola_B01_10_pp1_cluster_1             vF2A_T_40_NODE_165_length_1827_cov_2.740406
E_aphidicola_B01_5_pp1_cluster_3              vO3B_60_NODE_3075_length_3953_cov_65.144433
E_aphidicola_B01_5_pp3_cluster_2              vO2A_70_NODE_1755_length_2908_cov_20.712583
E_aphidicola_B03_6_pp2_cluster_7               vF2aA_40_NODE_88_length_21481_cov_7.525156
...                                                                                   ...
vZ3_NODE_99_length_4623_cov_3.405648             vZ3_40_NODE_342_length_1183_cov_2.327128
vZ3_T_30_NODE_17_length_2714_cov_4.069199       vZ3_T_30_NODE_17_length_2714_cov_4.069199
vZ3_T_30_NODE_49_length_1294_cov_4.116223       vZ3_T_30_NODE_49_length_1294_cov_4.116223
vZ3_T_50_NODE_25_length_3654_cov_5.442901       vZ3_T_50_NODE_25_length_3654_cov_5.442901
vZ3_T_NODE_11_length_9099_cov_12.047103    vOL_amp_30_NODE_220_length_6489_cov_121.915605

[187922 rows x 1 columns]

In [37]:
derreplicated_df_fixed[derreplicated_df_fixed["mem_d"]=="vZ2_T_70_NODE_1_length_47051_cov_58.060707"]

               rep                                       mem_d
716263  APSE_wheat  vZ2_T_70_NODE_1_length_47051_cov_58.060707